## Dataset

O nosso dataset providencia-nos dados geográficos e contagem de casos confirmados, óbitos e recuperados do Covid-19 num periodo de  4 meses (22 de janeiro de 2020 a 5 de maio de 2020) em vários países. O objetivo será extrair informação dos dados de forma a podermos construir um modelo de regressão capaz de prever as contagens tendo por base os fatores disponiveis (localização geográfica, dia e contagem anterior). Assim sendo é necessário partir dos dados iniciais e proceder a um pré-processamento para tratar os dados e poder-se então utlizar os algoritmos de regressão que pretendemos utilizar.

### Variáveis independentes

Como foi supramencionado, pretendemos utilizar certos fatores para fundamentarmos a nossa previsão (partindo dos dados do dataset). Estes então serão as coordenadas geográficas (Latitude e Longitude), número de dias desde o inicio da previsão (ou seja, 22 de janeiro) e contagens anteriores (número de casos confirmados, óbitos e recuperados do dia anterior).

### Variáveis Dependentes

Os valores que vamos prever serão os números de casos confirmados, óbitos e recuperados, sendo então estas as nossas variáveis independentes.

## Tratamento de dados

Para podermos obter resultados fiáveis, é preciso haver um tratamento dos dados que vem do dataset.
Pegando dos dados processados anteriormente feito inicialmente, começamos por extrai-los do ficheiro para podermos manipulá-los.

In [1]:
import pandas as pd

covid_data = pd.read_csv('covid_19_clean_complete.csv')
covid_data

Province/State         Country/Region        Lat       Long     Date  \
0                NaN            Afghanistan  33.000000  65.000000  1/22/20   
1                NaN                Albania  41.153300  20.168300  1/22/20   
2                NaN                Algeria  28.033900   1.659600  1/22/20   
3                NaN                Andorra  42.506300   1.521800  1/22/20   
4                NaN                 Angola -11.202700  17.873900  1/22/20   
...              ...                    ...        ...        ...      ...   
27451            NaN         Western Sahara  24.215500 -12.885800   5/4/20   
27452            NaN  Sao Tome and Principe   0.186360   6.613081   5/4/20   
27453            NaN                  Yemen  15.552727  48.516388   5/4/20   
27454            NaN                Comoros -11.645500  43.333300   5/4/20   
27455            NaN             Tajikistan  38.861034  71.276093   5/4/20   

       Confirmed  Deaths  Recovered  
0              0       0          0  
1              0       0          0  
2              0       0          0  
3              0       0          0  
4              0       0          0  
...          ...     ...        ...  
27451          6       0          5  
27452         23       3          4  
27453         12       2          0  
27454          3       0          0  
27455        230       3          0  

[27456 rows x 8 columns]

De seguida, após uma análise, verificou-se a presença de entrada respeitantes a navios que nalgum momento tiveram casos de Covid-19 e não estão portanto associados a nenhum país particular.
Além disso, consideramos que estes dados iriam criar ruído, pelo que optamos por ignorá-los e remover dos dados em análise.

In [2]:
covid_data = covid_data.drop(covid_data[covid_data['Province/State']=='Grand Princess'].index)
covid_data = covid_data.drop(covid_data[covid_data['Province/State']=='Diamond Princess'].index)
covid_data = covid_data.drop(covid_data[covid_data['Country/Region']=='Diamond Princess'].index)
covid_data = covid_data.drop(covid_data[covid_data['Country/Region']=='MS Zaandam'].index)
covid_data = covid_data.reset_index()
del covid_data['index']
covid_data

Province/State         Country/Region        Lat       Long     Date  \
0                NaN            Afghanistan  33.000000  65.000000  1/22/20   
1                NaN                Albania  41.153300  20.168300  1/22/20   
2                NaN                Algeria  28.033900   1.659600  1/22/20   
3                NaN                Andorra  42.506300   1.521800  1/22/20   
4                NaN                 Angola -11.202700  17.873900  1/22/20   
...              ...                    ...        ...        ...      ...   
27035            NaN         Western Sahara  24.215500 -12.885800   5/4/20   
27036            NaN  Sao Tome and Principe   0.186360   6.613081   5/4/20   
27037            NaN                  Yemen  15.552727  48.516388   5/4/20   
27038            NaN                Comoros -11.645500  43.333300   5/4/20   
27039            NaN             Tajikistan  38.861034  71.276093   5/4/20   

       Confirmed  Deaths  Recovered  
0              0       0          0  
1              0       0          0  
2              0       0          0  
3              0       0          0  
4              0       0          0  
...          ...     ...        ...  
27035          6       0          5  
27036         23       3          4  
27037         12       2          0  
27038          3       0          0  
27039        230       3          0  

[27040 rows x 8 columns]

A maioria das entradas da coluna **Province/State** tem valores nulos, pelo que procedemos a eliminá-los. Além disso, como ter uma entrada para uma região e país não é muito relevante, optamos por agregar as duas informações numa só coluna denominada de **Local**.

In [3]:
import numpy as np

covid_data['Province/State'] = covid_data.replace(np.nan, '', regex=True)
cols = ['Province/State', 'Country/Region']
covid_data['Local'] = covid_data[cols].apply(lambda row: ' / '.join(row.values.astype(str)) if row.values[0] != '' else ''.join(row.values.astype(str)), axis=1)
del covid_data['Province/State']
del covid_data['Country/Region']
covid_data

Lat       Long     Date  Confirmed  Deaths  Recovered  \
0      33.000000  65.000000  1/22/20          0       0          0   
1      41.153300  20.168300  1/22/20          0       0          0   
2      28.033900   1.659600  1/22/20          0       0          0   
3      42.506300   1.521800  1/22/20          0       0          0   
4     -11.202700  17.873900  1/22/20          0       0          0   
...          ...        ...      ...        ...     ...        ...   
27035  24.215500 -12.885800   5/4/20          6       0          5   
27036   0.186360   6.613081   5/4/20         23       3          4   
27037  15.552727  48.516388   5/4/20         12       2          0   
27038 -11.645500  43.333300   5/4/20          3       0          0   
27039  38.861034  71.276093   5/4/20        230       3          0   

                       Local  
0                Afghanistan  
1                    Albania  
2                    Algeria  
3                    Andorra  
4                     Angola  
...                      ...  
27035         Western Sahara  
27036  Sao Tome and Principe  
27037                  Yemen  
27038                Comoros  
27039             Tajikistan  

[27040 rows x 7 columns]

De seguida, vamos converter as datas em contagem de dias desde o início do dataset (22 de janeiro de 2020)

In [4]:
covid_data['Date'] = pd.to_datetime(covid_data['Date'],format='%m/%d/%y')
covid_data['Date'] -= pd.to_datetime("2020-01-22")
covid_data['Date'] /= np.timedelta64(1,'D')
covid_data = covid_data.rename(columns  = {'Date':'Days Passed'})



Por fim, adicionar as colunas da contagem do dia anterior. Este passo é um pouco mais longo tendo em conta o numero de linhas e a procura pelo valor anterior.

In [5]:
covid_data['Conf. Prev.'] = covid_data.apply(lambda row: 
                                                      covid_data[(covid_data['Local'] == row['Local']) & (covid_data['Days Passed'] == row['Days Passed']-1)]['Confirmed'].item()
                                                      if row['Days Passed'] > 0 else 0,axis=1)
covid_data['Deaths Prev.'] = covid_data.apply(lambda row: 
                                                      covid_data[(covid_data['Local'] == row['Local']) & (covid_data['Days Passed'] == row['Days Passed']-1)]['Deaths'].item()
                                                      if row['Days Passed'] > 0 else 0,axis=1)
covid_data['Recov. Prev.'] = covid_data.apply(lambda row: 
                                                      covid_data[(covid_data['Local'] == row['Local']) & (covid_data['Days Passed'] == row['Days Passed']-1)]['Recovered'].item()
                                                      if row['Days Passed'] > 0 else 0,axis=1)

covid_data

Lat       Long  Days Passed  Confirmed  Deaths  Recovered  \
0      33.000000  65.000000          0.0          0       0          0   
1      41.153300  20.168300          0.0          0       0          0   
2      28.033900   1.659600          0.0          0       0          0   
3      42.506300   1.521800          0.0          0       0          0   
4     -11.202700  17.873900          0.0          0       0          0   
...          ...        ...          ...        ...     ...        ...   
27035  24.215500 -12.885800        103.0          6       0          5   
27036   0.186360   6.613081        103.0         23       3          4   
27037  15.552727  48.516388        103.0         12       2          0   
27038 -11.645500  43.333300        103.0          3       0          0   
27039  38.861034  71.276093        103.0        230       3          0   

                       Local  Conf. Prev.  Deaths Prev.  Recov. Prev.  
0                Afghanistan            0             0             0  
1                    Albania            0             0             0  
2                    Algeria            0             0             0  
3                    Andorra            0             0             0  
4                     Angola            0             0             0  
...                      ...          ...           ...           ...  
27035         Western Sahara            6             0             5  
27036  Sao Tome and Principe           16             1             4  
27037                  Yemen           10             2             0  
27038                Comoros            3             0             0  
27039             Tajikistan          128             2             0  

[27040 rows x 10 columns]

In [6]:
with pd.ExcelWriter('covid_19_distance.xlsx') as writer:
    covid_data.to_excel(writer)

## Linear Regression

Fórmula de regressão linear:

[predicted_confirmed,predicted_deaths,predicted_recovered] = m1 * lat + m2 * long + m3 * days_passed + m4 * confirmed_previous_day + m5 * confirmed_previous_day + m6 * confirmed_previous_day + b

m1, m2, m3, m4, m5 and m6 são as matrizes coeficientes
b é a matriz residual

In [7]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split
reg = linear_model.LinearRegression()

#colunas em que vamos basear as previsões
x_columns = ['Lat','Long','Days Passed', 'Conf. Prev.', 'Deaths Prev.', 'Recov. Prev.']
#colunas que queremos prever
y_columns = ['Confirmed','Deaths','Recovered']

X_train, X_test, y_train, y_test = train_test_split(covid_data[x_columns], covid_data[y_columns], test_size=0.0096)
unscaled_test = X_test.join(y_test)

reg.fit(X_train,y_train)

LinearRegression()

In [8]:
print(reg.coef_)
print(reg.intercept_)

[[ 0.95821579 -0.25125869  1.01627033  1.05753823 -0.22306478 -0.05947577]
 [ 0.07581774 -0.01664749  0.05413497  0.00222319  1.01297888 -0.00375632]
 [ 0.07912743 -0.04484983  0.17107995  0.00912309 -0.03934519  1.01736811]]
[-19.41889543  -1.22483596  -2.24606868]


In [9]:
predictions = reg.predict(X_test)

In [10]:
#tratar dos resultados
predictions = pd.DataFrame(data=predictions,columns=['Confirmed Prediction','Deaths Prediction','Recovered Prediction'])

#buscar os locais para apresentar as previsoes, ja que nao foram usados no modelo de regressão
predictions['Local'] = unscaled_test.apply(lambda row: covid_data.loc[(covid_data['Lat'] == row['Lat']) & (covid_data['Long'] == row['Long']),'Local'].iloc[0],axis=1).tolist()

#arredondar os valores para inteiros, com teto
predictions['Confirmed Prediction'] = predictions['Confirmed Prediction'].apply(np.ceil)
predictions['Deaths Prediction'] = predictions['Deaths Prediction'].apply(np.ceil)
predictions['Recovered Prediction'] = predictions['Recovered Prediction'].apply(np.ceil)

#comparar os valores previstos e reais guardar a diferença nas contagens
predictions['Confirmed Diff'] = (unscaled_test['Confirmed'] - predictions['Confirmed Prediction'].values).tolist()
predictions['Deaths Diff'] = (unscaled_test['Deaths'] - predictions['Deaths Prediction'].values).tolist()
predictions['Recovered Diff'] = (unscaled_test['Recovered'] - predictions['Recovered Prediction'].values).tolist()
#colocar o numero de dias passados para ser mais facil analisar
predictions['Days Passed'] = unscaled_test['Days Passed'].tolist()

predictions = predictions[['Days Passed','Local', 'Confirmed Prediction', 'Confirmed Diff','Deaths Prediction', 'Deaths Diff','Recovered Prediction','Recovered Diff']]

In [11]:
predictions

Days Passed                   Local  Confirmed Prediction  \
0           79.0       Guangdong / China                1596.0   
1           78.0         Guizhou / China                 205.0   
2           94.0                 Albania                 799.0   
3           52.0                  Turkey                  68.0   
4           99.0        Mayotte / France                 530.0   
..           ...                     ...                   ...   
255         43.0    Heilongjiang / China                 543.0   
256         95.0               Nicaragua                 123.0   
257         51.0                 Finland                 150.0   
258         60.0  Bosnia and Herzegovina                 178.0   
259         12.0                Djibouti                  -6.0   

     Confirmed Diff  Deaths Prediction  Deaths Diff  Recovered Prediction  \
0             -52.0               10.0         -2.0                1470.0   
1             -59.0                6.0         -4.0                 157.0   
2             -87.0               35.0         -8.0                 423.0   
3             -63.0                4.0         -4.0                   9.0   
4               9.0                7.0         -3.0                 255.0   
..              ...                ...          ...                   ...   
255           -62.0               17.0         -4.0                   8.0   
256          -110.0               10.0         -7.0                  26.0   
257             5.0                7.0         -7.0                  12.0   
258           -52.0                7.0         -6.0                  14.0   
259             6.0               -0.0          0.0                  -1.0   

     Recovered Diff  
0             -36.0  
1             -13.0  
2             -20.0  
3              -9.0  
4             -20.0  
..              ...  
255            -8.0  
256           -19.0  
257           -11.0  
258           -12.0  
259             1.0  

[260 rows x 8 columns]

In [12]:
with pd.ExcelWriter('covid_19_linear_predictions.xlsx') as writer:
    predictions.to_excel(writer)